### ISSUE TITLE
Returns String rather than Response

### ISSUE THREAD

**Issue by farski** [jnunemaker/httparty#212]
I've seen this happen enough to know it's an issue, but we can't recreate the issue with any regularity. The problem is that (in our case) some small percentage of the time a #get is done, the object being returned is a String rather than an HTTParty::Response. This came about when using HTTParty in conjunction with Sidekiq to parse a large number of feeds.

I'm not seeing anything obvious in the code that could potentially lead to this situation, but it was happening enough that we had to switch to a different gem.

Anyone else seen this happen, and perhaps know what conditions cause it?

**Comment by zhaqiang** [comment]
I'm having a similar issue. Sometimes I got `nil` instead of an `HTTParty::Response` when a #get or #post is done. But I can't recreate the issue with any regularity, too. Here is my error message and backtrace:

```
 undefined method `body' for nil:NilClass
 /usr/local/lib/ruby/gems/2.3.0/gems/httparty-0.14.0/lib/httparty/request.rb:304:in `handle_deflation'

 -------------------------------
Backtrace:
-------------------------------

 /usr/local/lib/ruby/gems/2.3.0/gems/httparty-0.14.0/lib/httparty/request.rb:304:in `handle_deflation'
 /usr/local/lib/ruby/gems/2.3.0/gems/httparty-0.14.0/lib/httparty/request.rb:131:in `perform'
 /usr/local/lib/ruby/gems/2.3.0/gems/httparty-0.14.0/lib/httparty.rb:560:in `perform_request'
 /usr/local/lib/ruby/gems/2.3.0/gems/httparty-0.14.0/lib/httparty.rb:502:in `post'
 /usr/local/lib/ruby/gems/2.3.0/gems/httparty-0.14.0/lib/httparty.rb:602:in `post'
...
```

Not sure if it's ok to post the error in this issue.
