### ISSUE TITLE
 Undefined method `base_uri' for nil:NilClass Error in Production

### ISSUE THREAD

**Issue by demisx** [jnunemaker/httparty#289]
Hi. I have this service class:

``` ruby
module Services
  class ColdhouseReportsApiManager
    include HTTParty

    debug_output $stderr if Rails.env.development? 
    base_uri Settings.coldhouse_reports_api.base_uri
    ... ... ...
  end
end
```

Everything works fine in development. However, when try to start the rails server in production mode with `config.eager_load = true` I get the following error (works fine in development or if I set `config.eager_load = false`). Any idea why it wouldn't eager load? Thank you.

```
... app/services/coldhouse_reports_api_manager.rb:6:in `<class:ColdhouseReportsApiManager>': undefined method `base_uri' for nil:NilClass (NoMethodError)
    from /Users/dmoore/projects/webservices/syjregs-api/app/services/coldhouse_reports_api_manager.rb:2:in `<module:Services>'
    from /Users/dmoore/projects/webservices/syjregs-api/app/services/coldhouse_reports_api_manager.rb:1:in `<top (required)>'
    from /Users/dmoore/.rvm/gems/ruby-2.1.1@syjregs-api/gems/activesupport-4.1.0.rc2/lib/active_support/dependencies.rb:247:in `require'
    from /Users/dmoore/.rvm/gems/ruby-2.1.1@syjregs-api/gems/activesupport-4.1.0.rc2/lib/active_support/dependencies.rb:247:in `block in require'
    from /Users/dmoore/.rvm/gems/ruby-2.1.1@syjregs-api/gems/activesupport-4.1.0.rc2/lib/active_support/dependencies.rb:232:in `load_dependency'
    from /Users/dmoore/.rvm/gems/ruby-2.1.1@syjregs-api/gems/activesupport-4.1.0.rc2/lib/active_support/dependencies.rb:247:in `require'
    from /Users/dmoore/.rvm/gems/ruby-2.1.1@syjregs-api/gems/activesupport-4.1.0.rc2/lib/active_support/dependencies.rb:348:in `require_or_load'
    from /Users/dmoore/.rvm/gems/ruby-2.1.1@syjregs-api/gems/activesupport-4.1.0.rc2/lib/active_support/dependencies.rb:307:in `depend_on'
    from /Users/dmoore/.rvm/gems/ruby-2.1.1@syjregs-api/gems/activesupport-4.1.0.rc2/lib/active_support/dependencies.rb:225:in `require_dependency'
    from /Users/dmoore/.rvm/gems/ruby-2.1.1@syjregs-api/gems/railties-4.1.0.rc2/lib/rails/engine.rb:469:in `block (2 levels) in eager_load!'
    from /Users/dmoore/.rvm/gems/ruby-2.1.1@syjregs-api/gems/railties-4.1.0.rc2/lib/rails/engine.rb:468:in `each'
    from /Users/dmoore/.rvm/gems/ruby-2.1.1@syjregs-api/gems/railties-4.1.0.rc2/lib/rails/engine.rb:468:in `block in eager_load!'
```

**Comment by cdesch** [comment]
set it in the initializer or in another function

E.g.

```
module MyApp
  class MyAPIClass
    include HTTParty
    #base_uri 'myApiURL.com'  # <-- Normally like this
    #base_uri MyApp.configuration.base_url # <-- This won't work

    def login
      self.class.base_uri MyApp.configuration.base_url # <-- This will work but you must call `login`
      @options = "this_option"
      # ....more code logging in....
    end

    def day_parts
      self.class.get("/day-parts", @options)
    end
  end
end
```
