### ISSUE TITLE
SSL verify: false Ignores Port

### ISSUE THREAD

**Issue by superscott** [jnunemaker/httparty#370]
Would expect the following to work, but it seems like once **verify: false** is passed in it "defaults" to 443 and seems to ignore the passed in port.

**$ response = HTTParty.get('https://localhost:3780', verify: false)**
=> Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 443

However, if i set the service to run on 443, everything works fine.

**$ response = HTTParty.get('https://localhost', verify: false)**
=> okay.

ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin13]
httparty (0.13.3)

Let me know if there is any other information I can pass along.

**Comment by rusikf** [comment]
@superscott , i can't reproduce it, may be you made mistake?
It looks, that behaviour is nice
Without port it tries to use default port
```
[11] pry(main)> HTTParty.get 'https://localhost', verify: false
Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 443
from /home/ruslan/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/http.rb:879:in `initialize'
```
And with port everuthing is ok
```
[9] pry(main)> HTTParty.get 'https://localhost:3780', verify: false
=> "<!DOCTYPE html>\n<html>\n  <head>\n    <title>Ruby on Rails: Welcome aboard</title>\n    <style media=\"screen\">\n      body {\n        margin: 0;\n        margin-bottom: 25px;\n        padding: 0;\n        background-color: #f0f0f0;\n        font-family: \"Lucida Grande\", \"Bitstream Vera Sans\", \"Verdana\";\n        font-size: 13px;\n        color: #333;\n      }\n\n      h1 {\n        font-size: 28px;\n        color: #000;\n      }\n\n      a  {color: #03c}\n\n      a:hover {\n        background-color: #03c;\n        color: white;\n        text-decoration: none;\n      }\n\n      #page {\n        background-color: #f0f0f0;\n        width: 750px;\n        margin: 0;\n        margin-left: auto;\n        margin-right: auto;\n      }\n\n      #content {\n        float: left;\n        background-color: white;\n        border: 3px solid #aaa;\n        border-top: none;\n        padding: 25px;\n        width: 500px;\n      }\n\n      #sidebar {\n        float: right;\n        width: 175px;\n      }\n\n      #footer {\n        clear: both;\n      }\n\n      #header, #about, #getting-started {\n        padding-left: 75px;\n        padding-right: 30px;\n      }\n\n      #header {\n        background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAABACAYAAABY1SR7AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAGZhJREFUeNqsWwmUXGWV/t5Sr9aurl6qO0l3Z9/DEoJh18gZQGAUxPHIyQHH7eioZ8bjnAFHZ0RndNxxRBhGcUbxoKIHBkTEcUYREIHIGpKQjUDS6U660/tSVV3Lq/fefPf/Xy2dBFGYx3npqvde/e/e/97v3u/e/8e4Lt2L8DCCAFcGwF8ZBjYbgM1rAZoO+WLwZhDMu9y4+YcOozbAqzwXNA3GdzX/5hV+KnKO2+GXFj/AvzmW8e72iG202CYiphbY403f9/k3QHZtJ9oWtyCQe7wGX79TKVb7rP9pXJPDVxf0Rz+oyxm4HNWrahFNixdk3EAJbERMWOm4ulctVODNVeEVK0DeRVDgb1wfJgcqUo6duaKnFOH7bm6JmH+5LOEgZprwRIHAV3JYfLjKM55Noz3bBqdcgt0Wg52Kq/cHHkXns0qIukKBlltk9rU2QaiouiefPQ+RdBuseAJeqYTK1CTH8mE4NsyIpRWu8nssCs+xULWpjGVwTvieKl/sV6mIXzOib/OftzuG8d6l8SiVMODyRb46oazg8YPP2Wnvy9ISNqplzsxYAW6hjGhHEmYiBoPC+hRMfFMrESgrBC5n0KS+lq1nPahZh2OXymg9bSNWX/u3FKyKI//7Exx96B4Y8RiCEseq8t0VznyxjMDidFIJ8QSf3hJEOFbZEAHVhIkFTX54fxtnIW5pJUQIeZ8ooZShkInuDOLpFIX1ldtCBix7KI/k4E7OwbTjc[10] pry(main)> HTTParty.get 'https://localhost', verify: false
Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 443
from /home/ruslan/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/http.rb:879:in `initialize'
[11] pry(main)> HTTParty.get 'https://localhost', verify: false
Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 443
from /home/ruslan/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/http.rb:879:in `initialize'
[12] pry(main)> HTTParty.get 'https://localhost:3780', verify: false
=> "<!DOCTYPE html>\n<html>\n  <head>\n    <title>Ruby on Rails: Welcome aboard</title>\n    <style media=\"screen\">\n      body {\n        margin: 0;\n        margin-bottom: 25px;\n        padding: 0;\n        background-color: #f0f0f0;\n        font-family: \"Lucida Grande\", \"Bitstream Vera Sans\", \"Verdana\";\n        font-size: 13px;\n        color: #333;\n      }\n\n      h1 {\n        font-size: 28px;\n        color: #000;\n      }\n\n      a  {color: #03c}\n\n      a:hover {\n        background-color: #03c;\n        color: white;\n        text-decoration: none;\n      }\n\n      #page {\n        background-color: #f0f0f0;\n        width: 750px;\n        margin: 0;\n        margin-left: auto;\n        margin-right: auto;\n      }\n\n      #content {\n        float: left;\n        background-color: white;\n        border: 3px solid #aaa;\n        border-top: none;\n        padding: 25px;\n        width: 500px;\n      }\n\n      #sidebar {\n        float: right;\n        width: 175px;\n      }\n\n      #footer {\n        clear: both;\n      }\n\n      #header, #about, #getting-started {\n        padding-left: 75px;\n        padding-right: 30px;\n      }\n\n      #header {\n        background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAABACAYAAABY1SR7AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAGZhJREFUeNqsWwmUXGWV/t5Sr9aurl6qO0l3Z9/DEoJh18gZQGAUxPHIyQHH7eioZ8bjnAFHZ0RndNxxRBhGcUbxoKIHBkTEcUYREIHIGpKQjUDS6U660/tSVV3Lq/fefPf/Xy2dBFGYx3npqvde/e/e/97v3u/e/8e4Lt2L8DCCAFcGwF8ZBjYbgM1rAZoO+WLwZhDMu9y4+YcOozbAqzwXNA3GdzX/5hV+KnKO2+GXFj/AvzmW8e72iG202CYiphbY403f9/k3QHZtJ9oWtyCQe7wGX79TKVb7rP9pXJPDVxf0Rz+oyxm4HNWrahFNixdk3EAJbERMWOm4ulctVODNVeEVK0DeRVDgb1wfJgcqUo6duaKnFOH7bm6JmH+5LOEgZprwRIHAV3JYfLjKM55Noz3bBqdcgt0Wg52Kq/cHHkXns0qIukKBlltk9rU2QaiouiefPQ+RdBuseAJeqYTK1CTH8mE4NsyIpRWu8nssCs+xULWpjGVwTvieKl/sV6mIXzOib/OftzuG8d6l8SiVMODyRb46oazg8YPP2Wnvy9ISNqplzsxYAW6hjGhHEmYiBoPC+hRMfFMrESgrBC5n0KS+lq1nPahZh2OXymg9bSNWX/u3FKyKI//7Exx96B4Y8RiCEseq8t0VznyxjMDidFIJ8QSf3hJEOFbZEAHVhIkFTX54fxtnIW5pJUQIeZ8ooZShkInuDOLpFIX1ldtCBix7KI/k4E7OwbTjc:
```
I am using the same version 0.13.3
/cc @jnunemaker, @mikeastock

**Comment by superscott** [comment]
@rusikf -  I'll try it again with that version of Ruby

**Comment by superscott** [comment]
I get the same behavior using ruby 2.1.5

   
    [2] pry(main)> response = HTTParty.get('https://localhost:3780', verify: false)
    Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 443
    from /Users/sgreen/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:879:in `initialize'
    
    [3] pry(main)> HTTParty.get 'https://localhost', verify: false
    Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 443
    from /Users/sgreen/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:879:in `initialize'
    
    [4] pry(main)> HTTParty.get 'https://localhost:3780', verify: false
    Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 443
    from /Users/sgreen/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:879:in `initialize'
    
    [5] pry(main)> HTTParty.get 'https://localhost', verify: false
    => "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"

**Comment by meggersatmonsoon** [comment]
@superscott Is 3780 open? `netstat | grep 3780`
