### ISSUE TITLE
Class inside Module : uninitialized constant HTTParty::BasicObject (NameError)

### ISSUE THREAD

**Issue by calve** [jnunemaker/httparty#386]
Hi, 

it looks likes httparty fails to get included inside a class inside a module, as in  https://github.com/jnunemaker/httparty/blob/master/examples/aaws.rb, which fails with

```
/usr/lib/ruby/gems/2.2.0/gems/httparty-0.13.3/lib/httparty/response.rb:2:in `<module:HTTParty>': uninitialized constant HTTParty::BasicObject (NameError)
        from /usr/lib/ruby/gems/2.2.0/gems/httparty-0.13.3/lib/httparty/response.rb:1:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /tmp/httparty/lib/httparty.rb:603:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
        from aaws.rb:5:in `<main>'
```

My minimal reproducible case is
```
require 'httparty'
module MyModule
  class MyClass
    include HTTParty
   end
end
```

See also : http://stackoverflow.com/questions/29309838/why-am-i-getting-loaderror-or-nameerror-when-trying-to-use-httparty

**Comment by calve** [comment]
My bad ; I re-tested my minimal case which actually worked.
Turns out I included ``HTTPParty`` instead of ``HTTParty``
