### ISSUE TITLE
:local_host option raise error

### ISSUE THREAD

**Issue by mqzhang** [jnunemaker/httparty#387]
Find the local_host option from document here : http://www.rubydoc.info/github/jnunemaker/httparty/HTTParty/ClassMethods

But it keeps raising error : 

```
irb(main):005:0> HTTParty.get('http://test.com/',:local_host => '127.0.0.1')
Errno::EADDRNOTAVAIL: Can't assign requested address - connect(2)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `initialize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:877:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1367:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/httparty-0.13.3/lib/httparty/request.rb:98:in `perform'
	from /Library/Ruby/Gems/2.0.0/gems/httparty-0.13.3/lib/httparty.rb:539:in `perform_request'
	from /Library/Ruby/Gems/2.0.0/gems/httparty-0.13.3/lib/httparty.rb:475:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/httparty-0.13.3/lib/httparty.rb:577:in `get'
	from (irb):5
	from /usr/bin/irb:12:in `<main>'

irb(main):012:0> HTTParty.get('http://abc.com:8080/',:local_host => '127.0.0.1', :local_port => 8080)
Errno::EADDRINUSE: Address already in use - bind(2)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `initialize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:877:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1367:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/httparty-0.13.3/lib/httparty/request.rb:98:in `perform'
	from /Library/Ruby/Gems/2.0.0/gems/httparty-0.13.3/lib/httparty.rb:539:in `perform_request'
	from /Library/Ruby/Gems/2.0.0/gems/httparty-0.13.3/lib/httparty.rb:475:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/httparty-0.13.3/lib/httparty.rb:577:in `get'
	from (irb):12
	from /usr/bin/irb:12:in `<main>'
```

Local IP :
```
$ curl http://127.0.0.1:8080/
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
...

```

**Comment by jnunemaker** [comment]
I actually don't know much about this option. I've never used it. Must have been merged when I was away from the project. I'd hit up the mailing list on google groups as others may know more. If we confirm it is a bug on the list we can re-open the issue.
