### ISSUE TITLE
Command line utility for converting to xml prints empty line

### ISSUE THREAD

**Issue by shayonj** [jnunemaker/httparty#470]
For example:
```
httparty -f xml "http://jsonplaceholder.typicode.com/posts/1"
````
Returns empty line. Probably due to ```puts``` printing nothing at - https://github.com/jnunemaker/httparty/blob/2315322422f7de2ac5ef779030113a91f7b62736/bin/httparty#L113 ? Or maybe the line before didn't write out anything?

----
### Additional info:

Also doing:
```
httparty "http://jsonplaceholder.typicode.com/posts/1"
````
prints (STDOUT):

```
{"userId"=>1,
 "id"=>1,
 "title"=>
  "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
 "body"=>
  "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"}
```

Using JSON:
```
httparty -f json "http://jsonplaceholder.typicode.com/posts/1"
````
prints (STDOUT)

```json
{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}

```

And using CSV:
```
httparty -f csv "http://jsonplaceholder.typicode.com/posts/1"
````
breaks with 

```bash
/[Home-dir]/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1874:in `block (2 levels) in shift': Illegal quoting in line 2. (CSV::MalformedCSVError)
	from /[Home-dir]/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1836:in `each'
	from /[Home-dir]/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1836:in `block in shift'
	from /[Home-dir]/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1796:in `loop'
	from /[Home-dir]/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1796:in `shift'
	from /[Home-dir]/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1738:in `each'
	from /[Home-dir]/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1752:in `to_a'
	from /[Home-dir]/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1752:in `read'
	from /[Home-dir]/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1298:in `parse'
	from /[Home-dir]/.rvm/gems/ruby-2.2.1/gems/httparty-0.13.7/bin/httparty:116:in `<top (required)>'
	from /[Home-dir]/.rvm/gems/ruby-2.2.1/bin/httparty:23:in `load'
	from /[Home-dir]/.rvm/gems/ruby-2.2.1/bin/httparty:23:in `<main>'
	from /[Home-dir]/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /[Home-dir]/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```
maybe because its unable to parse the ```response.body``` as is.

**Comment by shayonj** [comment]
Might be of relevance for a potential solution (if any): http://codereview.stackexchange.com/questions/51569/building-xml-by-enumerating-through-array-hashes/51570#51570 :)

**Comment by shayonj** [comment]
Never mind, the understanding of the use-case was inverted :).
