### ISSUE TITLE
Test suite does not pass on Ruby 2.4

### ISSUE THREAD

**Issue by voxik** [jnunemaker/httparty#510]
The test suite fails on Ruby 2.4 with errors such as:

~~~
  1) HTTParty::Request::NON_RAILS_QUERY_STRING_NORMALIZER doesn't modify strings
     Failure/Error: expect(CGI.unescape(query_string)).to eq("foo=bar&foo=baz")
     NameError:
       uninitialized class variable @@accept_charset in #<Class:CGI>
     # ./spec/httparty/request_spec.rb:13:in `unescape'
     # ./spec/httparty/request_spec.rb:13:in `block (3 levels) in <top (required)>'
~~~

Since I believe this is bug in Ruby, I reported it upstream [[1]], so this is more or less just heads up ;)

[1]: https://bugs.ruby-lang.org/issues/13178

**Comment by Rsullivan00** [comment]
I have 4 different failures on ruby 2.4.1

```
Finished in 0.76511 seconds (files took 0.3414 seconds to load)
582 examples, 4 failures

Failed examples:

rspec ./spec/httparty/ssl_spec.rb:29 # HTTParty::Request SSL certificate verification should work when no trusted CA list is specified, even with a bogus hostname, when the verify option is set to true
rspec ./spec/httparty/ssl_spec.rb:33 # HTTParty::Request SSL certificate verification should work when using ssl_ca_file with a self-signed CA
rspec ./spec/httparty/ssl_spec.rb:37 # HTTParty::Request SSL certificate verification should work when using ssl_ca_file with a certificate authority
rspec ./spec/httparty/ssl_spec.rb:19 # HTTParty::Request SSL certificate verification should work when no trusted CA list is specified, when the verify option is set to false

Randomized with seed 42560
```
