### ISSUE TITLE
undefined method `empty?' for nil:NilClass

### ISSUE THREAD

**Issue by araslanov-e** [jnunemaker/httparty#514]
When run test (rspec) and when params have nil value - response 
```
undefined method `empty?' for nil:NilClass
     # /cache/bundler/ruby/2.1.0/gems/httparty-0.14.0/lib/httparty/hash_conversions.rb:29:in `normalize_param'
     # /cache/bundler/ruby/2.1.0/gems/httparty-0.14.0/lib/httparty/hash_conversions.rb:15:in `block in to_params'
     # /cache/bundler/ruby/2.1.0/gems/httparty-0.14.0/lib/httparty/hash_conversions.rb:15:in `each'
     # /cache/bundler/ruby/2.1.0/gems/httparty-0.14.0/lib/httparty/hash_conversions.rb:15:in `map'
     # /cache/bundler/ruby/2.1.0/gems/httparty-0.14.0/lib/httparty/hash_conversions.rb:15:in `to_params'
     # /cache/bundler/ruby/2.1.0/gems/httparty-0.14.0/lib/httparty/request.rb:166:in `normalize_query'
     # /cache/bundler/ruby/2.1.0/gems/httparty-0.14.0/lib/httparty/request.rb:147:in `body'
     # /cache/bundler/ruby/2.1.0/gems/httparty-0.14.0/lib/httparty/request.rb:176:in `setup_raw_request'
     # /cache/bundler/ruby/2.1.0/gems/httparty-0.14.0/lib/httparty/request.rb:115:in `perform'
     # /cache/bundler/ruby/2.1.0/gems/httparty-0.14.0/lib/httparty.rb:560:in `perform_request'
     # /cache/bundler/ruby/2.1.0/gems/httparty-0.14.0/lib/httparty.rb:502:in `post'
     # /cache/bundler/ruby/2.1.0/gems/httparty-0.14.0/lib/httparty.rb:602:in `post'
```
https://github.com/rspec/rspec-mocks/commit/1907cf9bd8ee735bc1f9bb16b8c8a346b391ba50
nil.respond_to?(:to_ary) => true

**Comment by jnunemaker** [comment]
I'm not really sure I understand the problem. Could you explain more and perhaps show some examples of what is wrong? Are you saying that the specs are currently failing for you? If so, what version of ruby? Are you saying that when you change something in a spec it begins to fail? If so, could you provide the diff of the changes? 

I'm going to close this right now since I can't verify the problem, but if you can provide more information we can dig into it together.
