### ISSUE TITLE
httparty-0.15.0.gem fail on windows

### ISSUE THREAD

**Issue by net1957** [jnunemaker/httparty#528]
````
ruby 2.2.6p396 (2016-11-15 revision 56800) [x64-mingw32]

Updating installed gems
Updating httparty
Fetching: httparty-0.15.0.gem (100%)
D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:388:in `symlink': symlink() function is unimplemented on this machine (NotImplementedError)
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:388:in `block (2 levels) in extract_tar_gz'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/package/tar_reader.rb:65:in `each'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:365:in `block in extract_tar_gz'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:459:in `block in open_tar_gz'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:456:in `wrap'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:456:in `open_tar_gz'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:364:in `extract_tar_gz'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:345:in `block (2 levels) in extract_files'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/package/tar_reader.rb:65:in `each'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:342:in `block in extract_files'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/package/file_source.rb:30:in `open'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/package/file_source.rb:30:in `with_read_io'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:339:in `extract_files'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:779:in `extract_files'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:302:in `install'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/resolver/specification.rb:97:in `install'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:166:in `block in install'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:156:in `each'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:156:in `install'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/dependency_installer.rb:405:in `install'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/commands/update_command.rb:213:in `update_gem'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/commands/update_command.rb:225:in `block in update_gems'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/commands/update_command.rb:224:in `each'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/commands/update_command.rb:224:in `update_gems'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/commands/update_command.rb:100:in `execute'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/command.rb:310:in `invoke_with_build_args'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/command_manager.rb:169:in `process_args'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/command_manager.rb:139:in `run'
        from D:/program/dvlt/ruby/ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/gem_runner.rb:55:in `run'
        from D:/program/dvlt/ruby/ruby22-x64/bin/gem:21:in `<main>'
---> unable to run `gem update`
````

all previous versions did install.
this is very annoying!!!

Regards

**Comment by mariotsi** [comment]
Same here, forcing the 0.14.0 at the moment!

**Comment by ahorek** [comment]
wait for https://github.com/jnunemaker/httparty/pull/527
or run the bundle update as an administrator (only if you're on Ruby 2.2+)

**Comment by net1957** [comment]
on windows8.1 I get the same error when I run it as administrator.
waiting on #527

**Comment by ahorek** [comment]
@net1957 sorry, it's up from Ruby 2.3 not Ruby 2.2+.

You need a system that supports symlinks which is Windows Vista+ and Ruby 2.3+.
Also you have to use a console elevated as administrator to create or modify symlinks. This restriction was removed in Windows 10: https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10

@jnunemaker could you take a look? please accept my PR or replace the symlink with a file. So we won't need any of these ugly hacks.

**Comment by jnunemaker** [comment]
Try 0.15.1 and let me know. Thanks!

**Comment by net1957** [comment]
Tried 0.15.1 on windows8.1 and ruby 233 : OK with elevated rights, It fail without.
on ruby226 it always fail.

Please remove this symlink.

Regards

**Comment by jnunemaker** [comment]
0.15.2 is out with symlink removed.

**Comment by net1957** [comment]
Thanks a lot!

**Comment by ahorek** [comment]
it works, thanks!
