### ISSUE TITLE
The change made in 0.15.4 breaks httparty if frozen_string_literal is set to true

### ISSUE THREAD

**Issue by mukilkrishnan** [jnunemaker/httparty#539]
The change made in 2f8093871b9bb6375f640c68145eb295733a97e2 breaks our builds because of the use of `gsub!`

```
RuntimeError:
       can't modify frozen String
     # ./vendor/bundle/ruby/2.3.0/gems/httparty-0.15.4/lib/httparty/parser.rb:105:in `gsub!'
     # ./vendor/bundle/ruby/2.3.0/gems/httparty-0.15.4/lib/httparty/parser.rb:105:in `parse'
     # ./vendor/bundle/ruby/2.3.0/gems/httparty-0.15.4/lib/httparty/parser.rb:67:in `call'
     # ./vendor/bundle/ruby/2.3.0/gems/httparty-0.15.4/lib/httparty/request.rb:383:in `parse_response'
     # ./vendor/bundle/ruby/2.3.0/gems/httparty-0.15.4/lib/httparty/request.rb:351:in `block in handle_response'
     # ./vendor/bundle/ruby/2.3.0/gems/httparty-0.15.4/lib/httparty/response.rb:25:in `parsed_response'
     # ./vendor/bundle/ruby/2.3.0/gems/httparty-0.15.4/lib/httparty/response.rb:88:in `method_missing'
```

We use Ruby 2.3.3 with the `# frozen_string_literal: true` magic comment in preparation for immutable strings in Ruby 3.0

**Comment by Rsullivan00** [comment]
Can you give this branch a try to verify it fixes your use case? https://github.com/jnunemaker/httparty/pull/540

**Comment by jnunemaker** [comment]
Merged the PR. I'll wait up to a day to cut a new release to ensure that this fixes the problem.

**Comment by mukilkrishnan** [comment]
@Rsullivan00 That does the trick. Thank you both 👍
