### ISSUE TITLE
API succeeds but returns EOFError

### ISSUE THREAD

**Issue by pawneetdev** [jnunemaker/httparty#580]
When I trigger an API using HTTParty, it gets executed but returns "EOFError: end of file reached". Following are the error logs:

	from /home/meet/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/openssl/buffering.rb:182:in `sysread_nonblock'
	from /home/meet/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/openssl/buffering.rb:182:in `read_nonblock'
	from /home/meet/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/net/protocol.rb:153:in `rbuf_fill'
	from /home/meet/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/net/protocol.rb:104:in `read'
	from /home/meet/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/net/http/response.rb:322:in `ensure in read_chunked'
	from /home/meet/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/net/http/response.rb:322:in `read_chunked'
	from /home/meet/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/net/http/response.rb:282:in `block in read_body_0'
	from /home/meet/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/net/http/response.rb:275:in `inflater'
	from /home/meet/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/net/http/response.rb:280:in `read_body_0'
	from /home/meet/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/net/http/response.rb:201:in `read_body'
	from /home/meet/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/net/http/response.rb:226:in `body'
	from /home/meet/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/net/http/response.rb:163:in `reading_body'
	from /home/meet/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/net/http.rb:1422:in `transport_request'
	from /home/meet/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/net/http.rb:1384:in `request'
	from /home/meet/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/net/http.rb:1377:in `block in request'
	from /home/meet/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/net/http.rb:853:in `start'
	from /home/meet/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/net/http.rb:1375:in `request'
	from /home/meet/.rvm/gems/ruby-2.1.9/gems/httparty-0.14.0/lib/httparty/request.rb:118:in `perform'
	from /home/meet/.rvm/gems/ruby-2.1.9/gems/httparty-0.14.0/lib/httparty.rb:560:in `perform_request'
	from /home/meet/.rvm/gems/ruby-2.1.9/gems/httparty-0.14.0/lib/httparty.rb:502:in `post'
	from /home/meet/.rvm/gems/ruby-2.1.9/gems/httparty-0.14.0/lib/httparty.rb:602:in `post'
	from (irb):77
	from /home/meet/.rvm/gems/ruby-2.1.9/gems/railties-4.2.1/lib/rails/commands/console.rb:110:in `start'
	from /home/meet/.rvm/gems/ruby-2.1.9/gems/railties-4.2.1/lib/rails/commands/console.rb:9:in `start'
	from /home/meet/.rvm/gems/ruby-2.1.9/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/meet/.rvm/gems/ruby-2.1.9/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/meet/.rvm/gems/ruby-2.1.9/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

**Comment by blazingkin** [comment]
Perhaps you are sending a null byte?
What is the POST request you are making?
