### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by ipatovanton** [jnunemaker/httparty#589]
I use Ruby '2.5.0'

My code 
```
class FeedEntry
  include Mongoid::Document
  include Mongoid::Timestamps

  field :guid, type: String
  field :url, type: String
  field :share_count, type: String

  before_update :share_info
  
  def share_info
    checked_url = self.url
    json_stats = HTTParty.get("http://api.sharedcount.com/?url=#{checked_url}&apikey=#{Rails.application.credentials.socialshared_api_key}")
    # parsed_stats = JSON.parse(json_stats)
    self.share_count = json_stats["Facebook"]["share_count"]
  end

end
```

When I try to update entries i got this:
```
NoMethodError: undefined method `[]' for nil:NilClass
/app/app/models/feed_entry.rb:67:in `share_info'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:605:in `catch'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:199:in `block in halting'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:513:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:513:in `invoke_before'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:131:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-6.1.1/lib/mongoid/interceptable.rb:132:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-6.1.1/lib/mongoid/persistable/updatable.rb:111:in `block in prepare_update'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:132:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-6.1.1/lib/mongoid/interceptable.rb:132:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-6.1.1/lib/mongoid/persistable/updatable.rb:110:in `prepare_update'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-6.1.1/lib/mongoid/persistable/updatable.rb:132:in `update_document'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-6.1.1/lib/mongoid/persistable/savable.rb:25:in `save'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-6.1.1/lib/mongoid/persistable/updatable.rb:46:in `update'
/app/app/models/feed_entry.rb:80:in `block in update_shares_three_hours'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-6.1.1/lib/mongoid/contextual/mongo.rb:696:in `yield_document'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-6.1.1/lib/mongoid/contextual/mongo.rb:133:in `block in each'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.5.2/lib/mongo/collection/view/iterable.rb:46:in `block in each'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.5.2/lib/mongo/cursor.rb:121:in `block in each'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.5.2/lib/mongo/cursor.rb:121:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.5.2/lib/mongo/cursor.rb:121:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.5.2/lib/mongo/collection/view/iterable.rb:45:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-6.1.1/lib/mongoid/query_cache.rb:222:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-6.1.1/lib/mongoid/contextual/mongo.rb:132:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-6.1.1/lib/mongoid/contextual.rb:20:in `each'
/app/app/models/feed_entry.rb:79:in `update_shares_three_hours'
/app/lib/tasks/feed.rake:6:in `block in <main>'
/app/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:27:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli.rb:360:in `exec'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli.rb:20:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli.rb:10:in `start'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/exe/bundle:30:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/exe/bundle:22:in `<top (required)>'
/app/bin/bundle:3:in `load'
/app/bin/bundle:3:in `<main>'
```

**Comment by jnunemaker** [comment]
That likely means `json_stats` or  `json_stats["Facebook"]` is `nil`. I'd check those by printing/debugging them to ensure they are non nil.
