### ISSUE TITLE
Querystring parameters do not seem to be URL-encoded correctly

### ISSUE THREAD

**Issue by jamietanna** [jnunemaker/httparty#697]
I've just been using HTTParty to integrate with an Apache Tomcat server, and noticed that all of my requests using _multiple_ querystring parameters fail. For instance, the below passes:

```
req=
https://www-api.jvt.me/micropub
{:q=>"source", :url=>"https://www.jvt.me/mf2/2020/04/wrofo/"}
{"Content-Type"=>"application/json", "Accept"=>"application/json"}
body=
{"type":["h-entry"],"properties":{"syndication":["https://brid.gy/publish/twitter"],"photo":[{"photo":"https://media.jvt.me/0231c1382a.jpeg","alt":"Zoom gallery view of the six attendees of Homebrew Website Club Nottingham, smiling at their respective cameras"}],"published":["2020-04-15T18:24:00+01:00"],"category":["homebrew-website-club","homebrew-website-club"],"content":[{"html":"","value":"Happy <a href=\"/tags/homebrew-website-club/\">#HomebrewWebsiteClub</a> from Nottingham! Socially distant, but coming together to work on stuff (quietly)"}]}}
```

But when sending multiple values in a given property, it fails.

```
req=
https://www-api.jvt.me/micropub
{:q=>"source", :url=>"https://www.jvt.me/mf2/2020/04/wrofo/", :properties=>["content", "category", "mp-syndicate-to", "mp-slug", "syndication", "published"]}
{"Content-Type"=>"application/json", "Accept"=>"application/json"}
body=
<!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>
```

Looking in the logs of Tomcat, when these requests are received, we see the following error:

```	
16-Apr-2020 15:08:14.083 INFO [http-nio-8080-exec-1] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
        java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
                at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:488)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:260)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Thread.java:748)
```	

This can be reproduced by running either of these Docker images:

```
docker run -it --rm -p 8888:8080 tomcat:8.5.53-jdk8-openjdk-slim
docker run -it --rm -p 8888:8080 tomcat:9-jdk8-openjdk-slim
```

And then sending a request to `localhost:8888`:

```ruby
require 'httparty'
p HTTParty.get('http://localhost:8888/', {query: {properties: ['f',2,3]}})
```

This can also be validated by running curl:

```
# without URL encoding (400 is expected)
curl 'localhost:8888?url=foo&properties[]=ff' -i
HTTP/1.1 400
Content-Type: text/html;charset=utf-8
Content-Language: en
Content-Length: 1943
Date: Thu, 16 Apr 2020 15:12:53 GMT
Connection: close

<!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Message</b> Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986</p><p><b>Description</b> The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).</p><p><b>Exception</b></p><pre>java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
        org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:488)
        org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:260)
        org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594)
        org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        java.lang.Thread.run(Thread.java:748)
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/9.0.33</h3></body></html>%
# with URL encoding (404 is expected)
curl 'localhost:8888?url=foo&properties%5B%5D=ff' -i
HTTP/1.1 404
Content-Type: text/html;charset=utf-8
Content-Language: en
Content-Length: 713
Date: Thu, 16 Apr 2020 15:13:37 GMT

<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Not found</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/9.0.33</h3></body></html>
```

It appears that it is due to https://github.com/jnunemaker/httparty/blob/7d16927fc67f1c20ea0743978b961e23a978d25c/lib/httparty/request.rb#L22-L45 not encoding the `key`, only the values.

Would you be happy receiving a PR to fix this?

**Comment by TheSmartnik** [comment]
@jamietanna thank you! Yeah, I'd be happy to receive a PR with the fix
