### ISSUE TITLE
1:50: FATAL: Space required after the Public Identifier (Nokogiri::XML::SyntaxError) in ruby 3.0.3

### ISSUE THREAD

**Issue by YannoteX** [jnunemaker/httparty#745]
Basically,
I'm trying to collect sitemaps urls with a ruby programm. I also collect the server response code with httparty like this : 

**def get_response_code(url)
        begin
            response = HTTParty.get(url)
        rescue
            return "error"
        end
        return response.code.to_s + " - " + response.message.to_s
    end**

And I got A big log that I'm unable to understand : 

_/home/hugo/.rvm/gems/ruby-3.0.3@scraping/gems/multi_xml-0.6.0/lib/multi_xml/parsers/nokogiri.rb:16:in `parse': 1:50: FATAL: Space required after the Public Identifier (Nokogiri::XML::SyntaxError)
	from /home/hugo/.rvm/gems/ruby-3.0.3@scraping/gems/multi_xml-0.6.0/lib/multi_xml.rb:146:in `parse'
	from /home/hugo/.rvm/gems/ruby-3.0.3@scraping/gems/httparty-0.20.0/lib/httparty/parser.rb:121:in `xml'
	from /home/hugo/.rvm/gems/ruby-3.0.3@scraping/gems/httparty-0.20.0/lib/httparty/parser.rb:148:in `parse_supported_format'
	from /home/hugo/.rvm/gems/ruby-3.0.3@scraping/gems/httparty-0.20.0/lib/httparty/parser.rb:112:in `parse'
	from /home/hugo/.rvm/gems/ruby-3.0.3@scraping/gems/httparty-0.20.0/lib/httparty/parser.rb:71:in `call'
	from /home/hugo/.rvm/gems/ruby-3.0.3@scraping/gems/httparty-0.20.0/lib/httparty/request.rb:358:in `parse_response'
	from /home/hugo/.rvm/gems/ruby-3.0.3@scraping/gems/httparty-0.20.0/lib/httparty/request.rb:326:in `block in handle_response'
	from /home/hugo/.rvm/gems/ruby-3.0.3@scraping/gems/httparty-0.20.0/lib/httparty/response.rb:37:in `parsed_response'
	from /home/hugo/.rvm/gems/ruby-3.0.3@scraping/gems/httparty-0.20.0/lib/httparty/response.rb:126:in `method_missing'
	from /home/hugo/Bureau/Markethings/Recherche_Mails/Scraper.rb:110:in `get_response_code'_

I'm using ruby 3.0.3 with httparty 0.20.0
Thanks for responding.

**Comment by YannoteX** [comment]
I figured out that i was trying to collect server response with the Sitemap url (wich ends with .xml) and not with the domain. I solved this one by myself sorry :)
