### ISSUE TITLE
Segmentation fault in request

### ISSUE THREAD

**Issue by gabrielsf14** [jnunemaker/httparty#781]
Hi, i'm trying to do a simple GET request HTTParty:
    
```
url = 'https://binamik-serverless-staging.vercel.app/api/conversion/orbapi'
response = HTTParty.get(url)
puts response
```

With another urls it works, only with this one it throws this error, have tried a lot of things without result. Above the log:

```
/usr/local/lib/ruby/2.7.0/net/protocol.rb:44: [BUG] Segmentation fault at 0x0020ffff92c4867c
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [aarch64-linux]
-- Control frame information -----------------------------------------------
c:0096 p:---- s:0644 e:000643 CFUNC  :connect_nonblock
c:0095 p:0064 s:0639 e:000638 METHOD /usr/local/lib/ruby/2.7.0/net/protocol.rb:44
c:0094 p:0620 s:0632 E:001c08 METHOD /usr/local/lib/ruby/2.7.0/net/http.rb:1009
c:0093 p:0003 s:0619 e:000618 METHOD /usr/local/lib/ruby/2.7.0/net/http.rb:943
c:0092 p:0028 s:0615 e:000614 METHOD /usr/local/lib/ruby/2.7.0/net/http.rb:932
c:0091 p:0012 s:0611 e:000610 METHOD /usr/local/lib/ruby/2.7.0/net/http.rb:1483
c:0090 p:0025 s:0603 e:000601 METHOD /usr/local/bundle/gems/httparty-0.18.1/lib/httparty/request.rb:145
c:0089 p:0068 s:0594 e:000593 METHOD /usr/local/bundle/gems/httparty-0.18.1/lib/httparty.rb:594
c:0088 p:0032 s:0586 e:000585 METHOD /usr/local/bundle/gems/httparty-0.18.1/lib/httparty.rb:508
c:0087 p:0019 s:0579 e:000578 METHOD /usr/local/bundle/gems/httparty-0.18.1/lib/httparty.rb:627
c:0086 p:0017 s:0573 e:000572 METHOD /siga/app/services/marketing_service.rb:35
c:0085 p:0051 s:0567 e:000566 METHOD /siga/app/use_cases/use_case/confirm_tickets.rb:19
c:0084 p:0009 s:0559 e:000558 BLOCK  /usr/local/bundle/gems/dry-monads-1.4.0/lib/dry/monads/do.rb:137
c:0083 p:0002 s:0556 e:000555 METHOD /usr/local/bundle/gems/dry-monads-1.4.0/lib/dry/monads/do/mixin.rb:40
c:0082 p:0026 s:0551 e:000550 METHOD /usr/local/bundle/gems/dry-monads-1.4.0/lib/dry/monads/do.rb:137
c:0081 p:0067 s:0545 e:000544 METHOD /siga/app/use_cases/use_case/create_reservation_payment.rb:99
c:0080 p:0009 s:0538 e:000537 BLOCK  /usr/local/bundle/gems/dry-monads-1.4.0/lib/dry/monads/do.rb:137
c:0079 p:0002 s:0535 e:000534 METHOD /usr/local/bundle/gems/dry-monads-1.4.0/lib/dry/monads/do/mixin.rb:40
c:0078 p:0026 s:0530 e:000529 METHOD /usr/local/bundle/gems/dry-monads-1.4.0/lib/dry/monads/do.rb:137
c:0077 p:0095 s:0524 e:000523 METHOD /siga/app/use_cases/use_case/create_reservation_payment.rb:36
c:0076 p:0009 s:0518 e:000517 BLOCK  /usr/local/bundle/gems/dry-monads-1.4.0/lib/dry/monads/do.rb:137
c:0075 p:0002 s:0515 e:000514 METHOD /usr/local/bundle/gems/dry-monads-1.4.0/lib/dry/monads/do/mixin.rb:40
c:0074 p:0026 s:0510 e:000509 METHOD /usr/local/bundle/gems/dry-monads-1.4.0/lib/dry/monads/do.rb:137
c:0073 p:0051 s:0504 e:000503 METHOD /siga/app/controllers/v1/reservation_payments_controller.rb:49
c:0072 p:0010 s:0498 e:000497 METHOD /usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_controller/metal/basic_implicit_render.rb:6
c:0071 p:0009 s:0492 e:000491 METHOD /usr/local/bundle/gems/actionpack-6.0.6.1/lib/abstract_controller/base.rb:195
c:0070 p:0024 s:0486 e:000485 METHOD /usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_controller/metal/rendering.rb:30
c:0069 p:0009 s:0481 e:000480 BLOCK  /usr/local/bundle/gems/actionpack-6.0.6.1/lib/abstract_controller/callbacks.rb:42
c:0068 p:0105 s:0478 E:000758 METHOD /usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:135
c:0067 p:0006 s:0468 E:000cc8 METHOD /usr/local/bundle/gems/actionpack-6.0.6.1/lib/abstract_controller/callbacks.rb:41
c:0066 p:0008 s:0463 e:000462 METHOD /usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_controller/metal/rescue.rb:22
c:0065 p:0009 s:0457 e:000456 BLOCK  /usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_controller/metal/instrumentation.rb:33
c:0064 p:0010 s:0453 e:000452 BLOCK  /usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/notifications.rb:180
c:0063 p:0022 s:0450 e:000449 METHOD /usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/notifications/instrumenter.rb:24
c:0062 p:0023 s:0442 e:000441 METHOD /usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/notifications.rb:180
c:0061 p:0095 s:0436 e:000435 METHOD /usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_controller/metal/instrumentation.rb:32
c:0060 p:0017 s:0430 e:000429 METHOD /usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_controller/metal/params_wrapper.rb:245
c:0059 p:0026 s:0425 e:000424 METHOD /usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/railties/controller_runtime.rb:27
c:0058 p:0077 s:0419 e:000418 METHOD /usr/local/bundle/gems/actionpack-6.0.6.1/lib/abstract_controller/base.rb:136
c:0057 p:0017 s:0412 e:000411 METHOD /usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_controller/metal.rb:190
c:0056 p:0034 s:0405 e:000404 METHOD /usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_controller/metal.rb:254
c:0055 p:0010 s:0398 e:000397 METHOD /usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/routing/route_set.rb:50
c:0054 p:0036 s:0390 e:000389 METHOD /usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/routing/route_set.rb:33
c:0053 p:0111 s:0382 e:000381 BLOCK  /usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/journey/router.rb:49 [FINISH]
c:0052 p:---- s:0370 e:000369 CFUNC  :each
c:0051 p:0008 s:0366 e:000365 METHOD /usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/journey/router.rb:32
c:0050 p:0042 s:0361 e:000360 METHOD /usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/routing/route_set.rb:834
c:0049 p:0023 s:0355 e:000354 METHOD /usr/local/bundle/gems/warden-jwt_auth-0.8.0/lib/warden/jwt_auth/middleware/token_dispatcher.rb:20
c:0048 p:0023 s:0347 e:000346 METHOD /usr/local/bundle/gems/warden-jwt_auth-0.8.0/lib/warden/jwt_auth/middleware/revocation_manager.rb:21
c:0047 p:0007 s:0341 e:000340 METHOD /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/builder.rb:244
c:0046 p:0059 s:0336 e:000335 METHOD /usr/local/bundle/gems/warden-jwt_auth-0.8.0/lib/warden/jwt_auth/middleware.rb:22
c:0045 p:0017 s:0330 e:000329 BLOCK  /usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:36 [FINISH]
c:0044 p:---- s:0327 e:000326 CFUNC  :catch
c:0043 p:0057 s:0322 e:000321 METHOD /usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:34
c:0042 p:0146 s:0316 e:000315 METHOD /usr/local/bundle/gems/versionist-2.0.1/lib/versionist/middleware.rb:39
c:0041 p:0007 s:0305 e:000304 METHOD /usr/local/bundle/gems/versionist-2.0.1/lib/versionist/middleware.rb:17
c:0040 p:0007 s:0300 e:000299 METHOD /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/etag.rb:27
c:0039 p:0039 s:0289 e:000288 METHOD /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/conditional_get.rb:40
c:0038 p:0007 s:0280 e:000279 METHOD /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/head.rb:12
c:0037 p:0065 s:0272 e:000271 METHOD /usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/migration.rb:567
c:0036 p:0008 s:0266 e:000265 BLOCK  /usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/middleware/callbacks.rb:27
c:0035 p:0024 s:0263 e:000262 METHOD /usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:101
c:0034 p:0009 s:0254 e:000253 METHOD /usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/middleware/callbacks.rb:26
c:0033 p:0016 s:0247 e:000246 METHOD /usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/middleware/executor.rb:14
c:0032 p:0033 s:0239 e:000238 METHOD /usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/middleware/actionable_exceptions.rb:18
c:0031 p:0052 s:0233 e:000232 METHOD /usr/local/bundle/gems/bugsnag-6.25.1/lib/bugsnag/integrations/rack.rb:51
c:0030 p:0026 s:0226 e:000225 METHOD /usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/middleware/debug_exceptions.rb:32
c:0029 p:0026 s:0215 e:000214 METHOD /usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/middleware/show_exceptions.rb:33
c:0028 p:0041 s:0208 E:001470 METHOD /usr/local/bundle/gems/railties-6.0.6.1/lib/rails/rack/logger.rb:37
c:0027 p:0008 s:0198 e:000197 BLOCK  /usr/local/bundle/gems/railties-6.0.6.1/lib/rails/rack/logger.rb:26
c:0026 p:0004 s:0195 e:000194 BLOCK  /usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/tagged_logging.rb:80
c:0025 p:0012 s:0192 e:000191 METHOD /usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/tagged_logging.rb:28
c:0024 p:0010 s:0186 e:000185 METHOD /usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/tagged_logging.rb:80
c:0023 p:0039 s:0181 e:000180 METHOD /usr/local/bundle/gems/railties-6.0.6.1/lib/rails/rack/logger.rb:26
c:0022 p:0052 s:0175 e:000174 METHOD /usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/middleware/remote_ip.rb:81
c:0021 p:0019 s:0169 e:000168 METHOD /usr/local/bundle/gems/request_store-1.5.1/lib/request_store/middleware.rb:19
c:0020 p:0038 s:0160 e:000159 METHOD /usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/middleware/request_id.rb:27
c:0019 p:0020 s:0154 e:000153 METHOD /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/runtime.rb:22
c:0018 p:0033 s:0144 e:000143 METHOD /usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29
c:0017 p:0016 s:0137 e:000136 METHOD /usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/middleware/executor.rb:14
c:0016 p:0077 s:0129 e:000128 METHOD /usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/middleware/static.rb:126
c:0015 p:0236 s:0121 e:000120 METHOD /usr/local/bundle/gems/rack-cors-1.1.1/lib/rack/cors.rb:100
c:0014 p:0007 s:0107 e:000106 METHOD /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/sendfile.rb:110
c:0013 p:0050 s:0095 e:000094 METHOD /usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/middleware/host_authorization.rb:103
c:0012 p:0236 s:0089 e:000088 METHOD /usr/local/bundle/gems/rack-cors-1.1.1/lib/rack/cors.rb:100
c:0011 p:0016 s:0075 e:000074 METHOD /usr/local/bundle/gems/railties-6.0.6.1/lib/rails/engine.rb:527
c:0010 p:0052 s:0069 e:000068 METHOD /usr/local/bundle/gems/prometheus-client-2.1.0/lib/prometheus/middleware/exporter.rb:32
c:0009 p:0079 s:0063 e:000062 METHOD /usr/local/bundle/gems/yabeda-prometheus-0.8.0/lib/yabeda/prometheus/exporter.rb:57
c:0008 p:0028 s:0057 e:000056 METHOD /usr/local/bundle/gems/puma-6.0.2/lib/puma/configuration.rb:268
c:0007 p:0008 s:0052 e:000051 BLOCK  /usr/local/bundle/gems/puma-6.0.2/lib/puma/request.rb:93
c:0006 p:0023 s:0049 e:000048 METHOD /usr/local/bundle/gems/puma-6.0.2/lib/puma/thread_pool.rb:340
c:0005 p:0370 s:0044 e:000043 METHOD /usr/local/bundle/gems/puma-6.0.2/lib/puma/request.rb:92
c:0004 p:0128 s:0029 e:000028 METHOD /usr/local/bundle/gems/puma-6.0.2/lib/puma/server.rb:429
c:0003 p:0006 s:0018 e:000017 BLOCK  /usr/local/bundle/gems/puma-6.0.2/lib/puma/server.rb:232
c:0002 p:0086 s:0014 e:000013 BLOCK  /usr/local/bundle/gems/puma-6.0.2/lib/puma/thread_pool.rb:147 [FINISH]
c:0001 p:---- s:0003 e:000002 (none) [FINISH]
rails_1     |
-- Ruby level backtrace information ----------------------------------------
/usr/local/bundle/gems/puma-6.0.2/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
/usr/local/bundle/gems/puma-6.0.2/lib/puma/server.rb:232:in `block in run'
/usr/local/bundle/gems/puma-6.0.2/lib/puma/server.rb:429:in `process_client'
/usr/local/bundle/gems/puma-6.0.2/lib/puma/request.rb:92:in `handle_request'
/usr/local/bundle/gems/puma-6.0.2/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
/usr/local/bundle/gems/puma-6.0.2/lib/puma/request.rb:93:in `block in handle_request'
/usr/local/bundle/gems/puma-6.0.2/lib/puma/configuration.rb:268:in `call'
/usr/local/bundle/gems/yabeda-prometheus-0.8.0/lib/yabeda/prometheus/exporter.rb:57:in `call'
/usr/local/bundle/gems/prometheus-client-2.1.0/lib/prometheus/middleware/exporter.rb:32:in `call'
/usr/local/bundle/gems/railties-6.0.6.1/lib/rails/engine.rb:527:in `call'
/usr/local/bundle/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/sendfile.rb:110:in `call'
/usr/local/bundle/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/middleware/static.rb:126:in `call'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/runtime.rb:22:in `call'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/local/bundle/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/usr/local/bundle/gems/railties-6.0.6.1/lib/rails/rack/logger.rb:26:in `call'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/tagged_logging.rb:80:in `tagged'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/tagged_logging.rb:28:in `tagged'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/usr/local/bundle/gems/railties-6.0.6.1/lib/rails/rack/logger.rb:26:in `block in call'
/usr/local/bundle/gems/railties-6.0.6.1/lib/rails/rack/logger.rb:37:in `call_app'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
/usr/local/bundle/gems/bugsnag-6.25.1/lib/bugsnag/integrations/rack.rb:51:in `call'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:101:in `run_callbacks'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/migration.rb:567:in `call'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/head.rb:12:in `call'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/conditional_get.rb:40:in `call'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/etag.rb:27:in `call'
/usr/local/bundle/gems/versionist-2.0.1/lib/versionist/middleware.rb:17:in `call'
/usr/local/bundle/gems/versionist-2.0.1/lib/versionist/middleware.rb:39:in `_call'
/usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
/usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
/usr/local/bundle/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
/usr/local/bundle/gems/warden-jwt_auth-0.8.0/lib/warden/jwt_auth/middleware.rb:22:in `call'
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/builder.rb:244:in `call'
/usr/local/bundle/gems/warden-jwt_auth-0.8.0/lib/warden/jwt_auth/middleware/revocation_manager.rb:21:in `call'
/usr/local/bundle/gems/warden-jwt_auth-0.8.0/lib/warden/jwt_auth/middleware/token_dispatcher.rb:20:in `call'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/routing/route_set.rb:834:in `call'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/journey/router.rb:32:in `serve'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/journey/router.rb:32:in `each'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/journey/router.rb:49:in `block in serve'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_controller/metal.rb:254:in `dispatch'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_controller/metal.rb:190:in `dispatch'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/abstract_controller/base.rb:136:in `process'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/notifications.rb:180:in `instrument'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/notifications.rb:180:in `block in instrument'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/abstract_controller/base.rb:195:in `process_action'
/usr/local/bundle/gems/actionpack-6.0.6.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/siga/app/controllers/v1/reservation_payments_controller.rb:49:in `create'
/usr/local/bundle/gems/dry-monads-1.4.0/lib/dry/monads/do.rb:137:in `call'
/usr/local/bundle/gems/dry-monads-1.4.0/lib/dry/monads/do/mixin.rb:40:in `call'
/usr/local/bundle/gems/dry-monads-1.4.0/lib/dry/monads/do.rb:137:in `block in call'
/siga/app/use_cases/use_case/create_reservation_payment.rb:36:in `call'
/usr/local/bundle/gems/dry-monads-1.4.0/lib/dry/monads/do.rb:137:in `confirm_tickets'
/usr/local/bundle/gems/dry-monads-1.4.0/lib/dry/monads/do/mixin.rb:40:in `call'
/usr/local/bundle/gems/dry-monads-1.4.0/lib/dry/monads/do.rb:137:in `block in confirm_tickets'
/siga/app/use_cases/use_case/create_reservation_payment.rb:99:in `confirm_tickets'
/usr/local/bundle/gems/dry-monads-1.4.0/lib/dry/monads/do.rb:137:in `call'
/usr/local/bundle/gems/dry-monads-1.4.0/lib/dry/monads/do/mixin.rb:40:in `call'
/usr/local/bundle/gems/dry-monads-1.4.0/lib/dry/monads/do.rb:137:in `block in call'
/siga/app/use_cases/use_case/confirm_tickets.rb:19:in `call'
/siga/app/services/marketing_service.rb:35:in `send_test'
/usr/local/bundle/gems/httparty-0.18.1/lib/httparty.rb:627:in `get'
/usr/local/bundle/gems/httparty-0.18.1/lib/httparty.rb:508:in `get'
/usr/local/bundle/gems/httparty-0.18.1/lib/httparty.rb:594:in `perform_request'
/usr/local/bundle/gems/httparty-0.18.1/lib/httparty/request.rb:145:in `perform'
/usr/local/lib/ruby/2.7.0/net/http.rb:1483:in `request'
/usr/local/lib/ruby/2.7.0/net/http.rb:932:in `start'
/usr/local/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
/usr/local/lib/ruby/2.7.0/net/http.rb:1009:in `connect'
/usr/local/lib/ruby/2.7.0/net/protocol.rb:44:in `ssl_socket_connect'
/usr/local/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock'

-- C level backtrace information -------------------------------------------
[1] - Worker 0 (PID: 36) booted in 0.02s, phase: 0
```

**Comment by JonMidhir** [comment]
@gabrielsf14 I'm on Arch and can't reproduce this with the gem. Can you provide more information? From the stack trace it looks like there's a lot more going on. This is at least run from a Rails application using Puma and wrapped by dry-monads. So it's not clear what's causing the Segfault, but testing HTTParty in isolation I can't reproduce it.
