### ISSUE TITLE
OpenSSL::SSL::SSLError

### ISSUE THREAD

**Issue by MR-X-junior** [jnunemaker/httparty#784]
```
irb(main):001:0> require 'httparty'
=> true
irb(main):002:0> HTTParty.get("https://mbasic.facebook.com")
/data/data/com.termux/files/usr/lib/ruby/3.2.0/openssl/buffering.rb:214:in `sysread_nonblock': SSL_read: unexpected eof while reading (OpenSSL::SSL::SSLError)
        from /data/data/com.termux/files/usr/lib/ruby/3.2.0/openssl/buffering.rb:214:in `read_nonblock'
        from /data/data/com.termux/files/usr/lib/ruby/3.2.0/net/protocol.rb:218:in `rbuf_fill'
        from /data/data/com.termux/files/usr/lib/ruby/3.2.0/net/protocol.rb:185:in `read_all'
        from /data/data/com.termux/files/usr/lib/ruby/3.2.0/net/http/response.rb:712:in `read_all'
        from /data/data/com.termux/files/usr/lib/ruby/3.2.0/net/http/response.rb:591:in `block in read_body_0'
        from /data/data/com.termux/files/usr/lib/ruby/3.2.0/net/http/response.rb:550:in `inflater'
        from /data/data/com.termux/files/usr/lib/ruby/3.2.0/net/http/response.rb:573:in `read_body_0'
        from /data/data/com.termux/files/usr/lib/ruby/3.2.0/net/http/response.rb:344:in `read_body'
        from /data/data/com.termux/files/usr/lib/ruby/3.2.0/net/http/response.rb:380:in `body'
        from /data/data/com.termux/files/usr/lib/ruby/3.2.0/net/http/response.rb:302:in `reading_body'
        from /data/data/com.termux/files/usr/lib/ruby/3.2.0/net/http.rb:1872:in `transport_request'
        from /data/data/com.termux/files/usr/lib/ruby/3.2.0/net/http.rb:1826:in `request'
        from /data/data/com.termux/files/usr/lib/ruby/3.2.0/net/http.rb:1819:in `block in request'
        from /data/data/com.termux/files/usr/lib/ruby/3.2.0/net/http.rb:1238:in `start'
        from /data/data/com.termux/files/usr/lib/ruby/3.2.0/net/http.rb:1817:in `request'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/httparty-0.21.0/lib/httparty/request.rb:156:in `perform'
        ... 7 levels...
```

**Comment by rgalanakis** [comment]
I am hitting this as well (though with a totally different site: https://www.portlandonline.com/shared/cfm/trackit_devicerss.cfm

I have tried `HTTParty.get('https://www.portlandonline.com/shared/cfm/trackit_devicerss.cfm')` on my macbook pro (Ventura 13.2), and also from a Heroku dyno.

`verify: false` has no effect.

Using `Net::HTTP.get URI('https://www.portlandonline.com/shared/cfm/trackit_devicerss.cfm')` works fine.

However this errors:

```
[6] pry(main)> uri = URI('https://www.portlandonline.com/shared/cfm/trackit_devicerss.cfm')
req = Net::HTTP::Get.new(uri)
res = Net::HTTP.start(uri.hostname, uri.port) {|http|
  http.request(req)
}
Errno::ECONNRESET: Connection reset by peer
from <internal:io>:63:in `read_nonblock'
```

This seems like a system-level problem but I'm not sure what it can be. Other sites (google.com for example) work ok. I can't find any unexpected problems (for example the facebook url uses TLS 1.3 and HTTP/2, and the cert is good).

**Comment by rgalanakis** [comment]
This works: `HTTParty.get('https://mbasic.facebook.com', headers: {'Connection' => 'keep-alive'})`
I notice that `Net::HTTP` does this:
```
        start {
          req['connection'] ||= 'close'
          return request(req, body, &block)
        }
```
